@startuml DeploymentView
package "Система" {
  [Web Сървър] <<Server>>
  [База Данни] <<Server>>
  [Identity API] <<Server>>

  [Кеш Сървър] <<Server>>
}

package "Клиенти" {
  [Работна Станция] <<Device>>
  [Мобилно Устройство] <<Device>>
}

package "Потребителска Интеракция" {
  [Web Браузър] <<Browser>>
  [Мобилно Приложение] <<Mobile App>>
}

[Работна Станция] --> [Web Браузър] : "Отваря уеб сайт"
[Мобилно Устройство] --> [Мобилно Приложение] : "Изпраща HTTP Заявка"
[Web Браузър] --> [Web Сървър] : "HTTP Заявка"
[Мобилно Приложение] --> [Web Сървър] : "HTTP Заявка"

[Web Сървър] --> [Identity API] : "Аутентикация"
[Web Сървър] --> [База Данни] : "SQL Заявка"
[Web Сървър] --> [Кеш Сървър] : "Кеширане на данни"

[База Данни] --> [Кеш Сървър] : "Обновяване на кеша"
[Кеш Сървър] --> [Web Сървър] : "Бързо предоставяне на данни"
@enduml
